use systemd modprobe service for speakup_soft
linux-speakup/espeakup pull request #37
Opened 2021-06-29 16:14 UTC by williamh

2021-06-29 21:51 UTC, alex19EP requested changes
I think we can improve unit further. see my suggestions.

I need to test this. and also read the systemd-unit manual again.

2021-06-29 21:51 UTC, alex19EP commented on services/systemd/espeakup.service.in
>  Wants=systemd-udev-settle.service
```suggestion
Wants=modprobe@speakup_soft.service
```

2021-06-29 21:51 UTC, alex19EP commented on services/systemd/espeakup.service.in
> +After=modprobe@speakup_soft.service systemd-udev-settle.service sound.target
```suggestion
After=modprobe@speakup_soft.service sound.target
```

2021-07-03 18:45 UTC, williamh commented
@alex19EP  ping?

2021-07-03 20:36 UTC, alex19EP approved these changes

2021-07-03 20:37 UTC, merged